name: "App Workflow"

on:
  workflow_call: 
    inputs:
      aws-assume-role-arn:
        type: string
        required: true
      aws-region:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: cd app && npm install

      - name: Build Angular Project
        run: cd app && npm run build

      - name: Save build
        uses: actions/upload-artifact@master
        with:
          name: build
          path: app/dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Get build
        uses: actions/download-artifact@master
        with:
          name: build
          path: app/dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws-region }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./app/dist/browser s3://dev-sa-east-1-study-pipeline/
