name: "DEV - DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    uses: ./.github/workflows/infra.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::292892668466:role/github-actions-carlostomazin-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "carlostomazin-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "carlostomazin-sa-east-1-terraform-lock"

  app:
    uses: ./.github/workflows/app.yml
    needs: infra
    with:
      aws-assume-role-arn: "arn:aws:iam::292892668466:role/github-actions-carlostomazin-pipeline"
      aws-region: "sa-east-1"