name: "DEV - DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::292892668466:role/github-actions-carlostomazin-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "carlostomazin-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "carlostomazin-sa-east-1-terraform-lock"

  open_pull_request:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Git CLI
        run: |
          sudo apt-get install git

      - name: Buscar branch principal
        run: git fetch origin main

      - name: Criar pull request
        run: |
          git checkout develop
          gh pr create -f -m "Atualizar main com as últimas alterações do develop"