name: "DEV - DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::292892668466:role/github-actions-carlostomazin-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "carlostomazin-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "carlostomazin-sa-east-1-terraform-lock"
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6